### ISSUE TITLE
flake8 3.6.0 fixes

### ISSUE THREAD

**Issue by sbesson** [ome/omero-test-infra#26]
The [3.6.0 release of flake](http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html) includes a bump to the version of the `pycodestyle` which is incompatible with the capping of this dependency introduced in #17. As a result, most of the Python apps/plugins which Travis build consumes `omero-test-infra` now fail with an `ImportError` - see https://travis-ci.org/sbesson/omero-plugins/builds/450260239 for the full list.

### Option 1: cap `flake8`

This is the most short-term solution and should fix most the Travis builds - see https://travis-ci.org/sbesson/omero-plugins/builds/450260382.

### Option 2: uncap `pycodestyle`

This should prevent the `ImportError` and let the plugins/apps be validated by `flake8 3.6.0`. https://travis-ci.org/sbesson/omero-plugins/builds/450260479 suggests that additional work might be required to fix some of the new warnings reported as error

In both cases, it is worth noting that `omero-parade` fails with another error which might need to be addressed separately.

**Comment by jburel** [comment]
https://github.com/openmicroscopy/omero-test-infra/pull/27 for option 1 
We can look at option 2 later on

**Comment by jburel** [comment]
no longer valid
