### ISSUE TITLE
flake8 version is different from openmicroscopy

### ISSUE THREAD

**Issue by manics** [ome/omero-test-infra#33]
[openmicroscopy/openmicroscopy requires `flake8==2.4.0`](https://github.com/openmicroscopy/openmicroscopy/blob/v5.5.0-m2/.travis.yml#L47)
[This repo requires `flake8<3.6.0` (currently `3.5.0`)](https://github.com/openmicroscopy/omero-test-infra/blob/v0.3.7/requirements.txt#L1) which has slightly different rules.

This means separate environments are required for developing OMERO.py and plugins.

**Comment by jburel** [comment]
No longer valid
